<a href="https://colab.research.google.com/github/IrumShehryar/ML-NLP-Coursework/blob/main/machine-learning/Project02_Data_Standardization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

## Creating dataset

In [2]:
x1 = np.array([0,1,2,3,4,5,6,7,8,9])

In [3]:
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
x1.shape

(10,)

In [5]:
x1 = x1.reshape(-1,1)

In [6]:
x1

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [7]:
x1.shape

(10, 1)

In [8]:
x2 = np.array([201,220,233,243,257,269,272,283,299,339])

In [9]:
x2 = x2.reshape(-1,1)

In [10]:
x2

array([[201],
       [220],
       [233],
       [243],
       [257],
       [269],
       [272],
       [283],
       [299],
       [339]])

In [11]:
x3 = np.array([2000, 3550, 2350, 3940, 4000, 50000, 2677, 9765, 8876, 9776]).reshape(-1,1)
x3

array([[ 2000],
       [ 3550],
       [ 2350],
       [ 3940],
       [ 4000],
       [50000],
       [ 2677],
       [ 9765],
       [ 8876],
       [ 9776]])

In [12]:
X = np.hstack((x1,x2,x3))

In [13]:
X

array([[    0,   201,  2000],
       [    1,   220,  3550],
       [    2,   233,  2350],
       [    3,   243,  3940],
       [    4,   257,  4000],
       [    5,   269, 50000],
       [    6,   272,  2677],
       [    7,   283,  9765],
       [    8,   299,  8876],
       [    9,   339,  9776]])

In [14]:
y = np.array([10,20,30,40,50,60,70,80,90,100])
y

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

# Splitting the Data

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

# Data Standardization

In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
sc = StandardScaler()

In [18]:
sc.fit(X_train) # Compute the mean and standard deviation to be used for later scaling.


StandardScaler()

In [19]:
X_train_scaled = sc.transform(X_train) # Scaling the data according to the calculated mean and standard deviation

In [20]:
X_train_scaled

array([[ 0.18569534,  0.18159135,  2.59582878],
       [-1.67125804, -1.61451218, -0.56367527],
       [ 0.92847669,  0.55137737, -0.05255967],
       [-0.92847669, -0.76928699, -0.54063722],
       [ 1.67125804,  2.03052146, -0.05183561],
       [-0.18569534, -0.1353681 , -0.43202927],
       [-0.55708601, -0.50515412, -0.43597865],
       [ 0.55708601,  0.26083121, -0.5191131 ]])

# Mean and Standard deviation of Standardized data

In [21]:
X_train_scaled.mean()

np.float64(0.0)

In [22]:
X_train_scaled.std()

np.float64(1.0)

# Standardized the test data

In [23]:
X_test_scaled = sc.transform(X_test)

In [27]:
X_test_scaled.mean()

np.float64(-0.11856594837078878)

In [26]:
X_test_scaled.std()

np.float64(0.9752853836687363)

In [24]:
X_test_scaled

array([[ 1.29986737,  0.97398997, -0.11107631],
       [-1.29986737, -1.11265973, -0.46164962]])