<a href="https://colab.research.google.com/github/IrumShehryar/ML-NLP-Coursework/blob/main/machine-learning/02_Dealing_with_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# An array is a data structure which stores the values of the same type.

In [ ]:
import numpy as np   # NumPy is a Python Library that provides arrays

In [1]:
import numpy as np

# Generating one-dimensional (1D) array.

In [ ]:
a = np.array([0,1,2,3,4,5,6,7,8,9])

In [2]:
a= np.array([0,1,2,3,4,5,6,7,8,9])

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a

# Generating two-dimensional (2D) array.

In [ ]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Checking the shape (dimension) and size of the array.

In [ ]:
a.shape

In [7]:
a.shape

(10,)

In [8]:
b.shape

(3, 3)

In [ ]:
b.shape

In [9]:
a.size

10

In [ ]:
a.size

In [ ]:
b.size

In [10]:
b.size

9

# Check the type

In [ ]:
type(a)             # Type of data structure

In [12]:
type(a)

numpy.ndarray

In [ ]:
type(b)

In [13]:
type(b)

numpy.ndarray

In [ ]:
a.dtype             # dtype means data type. The type of a value i.e integer or float.

In [14]:
a.dtype

dtype('int64')

In [ ]:
b.dtype

In [15]:
b.dtype

dtype('int64')

# Maximum and Minimum values

In [16]:
a = np.array([0,1,2,3,4,5,6,7,8,9])

In [17]:
np.max(a)

np.int64(9)

In [ ]:
np.max(a)

In [18]:
np.min(a)

np.int64(0)

In [ ]:
np.min(a)

# Index of maximum and minimum values

In [19]:
a = np.array([4,2,3,13,5,7,14])

In [20]:
max(a)

np.int64(14)

In [ ]:
max(a)

In [21]:
a.max()

np.int64(14)

In [ ]:
a.max()    # finding maximum value

In [ ]:
a.argmax() # index of maximum value

In [22]:
a.argmax()

np.int64(6)

In [ ]:
a.min()  # finding minimum value

In [23]:
a.min()

np.int64(2)

In [24]:
a.argmin()

np.int64(1)

In [ ]:
a.argmin() # index of minimum value

# arange

In [ ]:
c = np.arange(0,10)
c

In [26]:
c=np.arange(0,10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,11)

In [27]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
d = np.arange(0,11,2)
d

In [29]:
d=np.arange(0,11,2)
d

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
e = np.arange(0,101,20)
e

In [30]:
e=np.arange(0,101,20)
e

array([  0,  20,  40,  60,  80, 100])

# linspace

In [ ]:
x1 = np.linspace(0,20,5)
x1

In [31]:
x1=np.linspace(0,20,5)
x1

array([ 0.,  5., 10., 15., 20.])

In [ ]:
x2 = np.linspace(0,10,3)

In [32]:
x2=np.linspace(0,10,3)
x2

array([ 0.,  5., 10.])

In [ ]:
x2

In [ ]:
x3 = np.linspace(0,10,50)

In [33]:
x3=np.linspace(0,10,50)
x3

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [ ]:
x3

In [ ]:
x3.shape

In [34]:
x3.shape

(50,)

# reshape

In [ ]:
y = np.arange(0,25)
y

In [35]:
y=np.arange(0,25)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
y.shape

In [36]:
y.shape

(25,)

In [ ]:
y.reshape(5,5)

In [37]:
y.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
y.reshape(1,25)

In [38]:
y.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
y.reshape(25,1)

In [39]:
y.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

# zeros and ones

In [ ]:
np.zeros(3)

In [40]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros(shape=(3,3))

In [41]:
np.zeros(shape=(3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((3,3))

In [43]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones(5)

In [44]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((4,3))

In [45]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
7 * np.ones((3,3))

In [46]:
7*np.ones((3,3))

array([[7., 7., 7.],
       [7., 7., 7.],
       [7., 7., 7.]])

# eye, generating Identity matrix

In [ ]:
np.eye(3)

In [47]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Random Numbers

## randn

In [ ]:
x1 = np.random.randn(3,3)                    # will generate random numbers from normal distribution.
x1

In [49]:
x1=np.random.randn(3,3)
x1

array([[-0.22356375, -0.41682475,  0.03949922],
       [-0.01080456, -0.9738867 , -1.25408469],
       [ 1.16057699, -1.11082159, -0.3782022 ]])

## rand

In [58]:
x2 = np.random.rand(3,3)                          # will generate random numbers between 0 and 1.
x2

array([[0.00127424, 0.16062614, 0.15962552],
       [0.72574327, 0.33112849, 0.72111996],
       [0.15986304, 0.33157913, 0.64886117]])

In [53]:
x2=np.random.rand(3,3)
x2

array([[0.49730879, 0.67527342, 0.44193239],
       [0.6322657 , 0.43142789, 0.36478141],
       [0.27092177, 0.11057961, 0.35181506]])

## randint

In [ ]:
x3 = np.random.randint(3,8,10)                  # will generate 10 random integers between 3 and 8.
x3

In [57]:
x3=np.random.randint(3,8,10)
x3

array([4, 6, 5, 4, 7, 6, 5, 3, 5, 3])

# Indexing and Slicing

## Indexing and slicing with 1D array

In [ ]:
ar = np.array([4,2,3,13,5,7,14])
ar

In [59]:
ar=np.array([4,2,3,13,5,7,14])
ar

array([ 4,  2,  3, 13,  5,  7, 14])

In [ ]:
ar[3]  # Indexing

In [60]:
ar[3]

np.int64(13)

In [ ]:
ar[6]

In [61]:
ar[6]

np.int64(14)

In [ ]:
ar[1:4]  # Slicing

In [62]:
ar[1:4]

array([ 2,  3, 13])

In [ ]:
ar[-1]  # Extracting last member of array.

In [63]:
ar[-1]

np.int64(14)

In [ ]:
ar[-2] # Extracting second last memeber of array

In [64]:
ar[-2]

np.int64(7)

In [ ]:
ar[1:]  # Slicing from index 1 to end.

In [65]:
ar[1:]

array([ 2,  3, 13,  5,  7, 14])

In [ ]:
ar[:4]  # slicing upto index 3

In [66]:
ar[:4]

array([ 4,  2,  3, 13])

In [ ]:
ar[:-1]  # Include everything except the last member of array

In [67]:
ar[:-1]

array([ 4,  2,  3, 13,  5,  7])

In [ ]:
ar[::-1]  # Reversing or flipping the array

In [68]:
ar[::-1]

array([14,  7,  5, 13,  3,  2,  4])

## Indexing of sub-array and sub-matrix from 2D (matrix) array

In [ ]:
arr = np.arange(1,17).reshape(4,4)
arr

In [81]:
arr=np.arange(1,17)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [84]:
arr1 = arr.reshape(4,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
arr[0] # Extracting first row

In [85]:
arr1[0]

array([1, 2, 3, 4])

In [ ]:
arr[3] # Extracting last row

In [86]:
arr1[3]

array([13, 14, 15, 16])

In [79]:
arr[2][1]

IndexError: invalid index to scalar variable.

In [87]:
arr1[2][1]

np.int64(10)

In [77]:
arr[2,1] # Other method

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
arr[1:3,1:3]

In [92]:
arr1[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [89]:
arr1[2,1]

np.int64(10)

In [ ]:
arr[:,3]   # Extracting last column

In [91]:
arr1[:,3]

array([ 4,  8, 12, 16])

In [94]:
arr1[:,3].reshape(-1,1)

array([[ 4],
       [ 8],
       [12],
       [16]])

In [ ]:
arr[:,3].reshape(-1,1)  # Extracting last column vertically

In [ ]:
arr[:,3:]  # Other way of Extracting last column vertically

In [95]:
arr1[:,3:]

array([[ 4],
       [ 8],
       [12],
       [16]])