<a href="https://colab.research.google.com/github/IrumShehryar/ML-NLP-Coursework/blob/main/nlp/04-neural-network/neural-word-embeddings/Project01_ImplementingCBOW_SmallCorpus.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Libraries

In [2]:
from nltk.tokenize import word_tokenize
import numpy as np
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

# Create a sentence and tokenize it

In [3]:
sentence = "Quick and cute white cat jumps over the lazy rabbit"

In [4]:
tokenized_sentence = word_tokenize(sentence.lower())

In [5]:
tokenized_sentence

['quick',
 'and',
 'cute',
 'white',
 'cat',
 'jumps',
 'over',
 'the',
 'lazy',
 'rabbit']

In [6]:
len(tokenized_sentence)

10

# Iterate over the tokenized sentence

In [7]:
for index, word in enumerate(tokenized_sentence):
  print(index, word)

0 quick
1 and
2 cute
3 white
4 cat
5 jumps
6 over
7 the
8 lazy
9 rabbit


# With neighbors = 2, iterate only once over the tokenized_sentence

In [8]:
neighbors = 2
for index, word in enumerate(tokenized_sentence):
  break
start = max(0, index - neighbors) # avoid negative index

In [9]:
print("index :", index)
print(" ")
print("index-neighbors :", index-neighbors)
print(" ")
print("start = max(0, index - neighbors) :", start)
print(" ")
print("Word :", word)

index : 0
 
index-neighbors : -2
 
start = max(0, index - neighbors) : 0
 
Word : quick


# Print the tokenized sentence with start and finish indices

In [10]:
neighbors = 2
for index, word in enumerate(tokenized_sentence):
  if index == 10:
   break
start = max(0, index - neighbors) # avoid negative index
finish = min(len(tokenized_sentence), index + neighbors + 1) # to control the overflow of the sentence


print("index :", index)
print(" ")
print("word :", word)
print(" ")
print("index-neighbors :", index-neighbors)
print(" ")
print("start = max(0, index - neighbors) :", start)
print(" ")
print("index + neighbors + 1 :", index + neighbors + 1)
print(" ")
print("len(tokenized_sentence)", len(tokenized_sentence))
print(" ")
print("finish = min(len(tokenized_sentence), index + neighbors + 1) :", finish)
print(" ")
print("tokenized_sentence[start : finish] : ", tokenized_sentence[start : finish])

index : 9
 
word : rabbit
 
index-neighbors : 7
 
start = max(0, index - neighbors) : 7
 
index + neighbors + 1 : 12
 
len(tokenized_sentence) 10
 
finish = min(len(tokenized_sentence), index + neighbors + 1) : 10
 
tokenized_sentence[start : finish] :  ['the', 'lazy', 'rabbit']


# Lets Print Every Sentence

In [11]:
neighbors = 2

for index, word in enumerate(tokenized_sentence):
    start = max(0, index - neighbors)
    finish = min(len(tokenized_sentence), index + neighbors + 1)
    print(tokenized_sentence[start:finish])

['quick', 'and', 'cute']
['quick', 'and', 'cute', 'white']
['quick', 'and', 'cute', 'white', 'cat']
['and', 'cute', 'white', 'cat', 'jumps']
['cute', 'white', 'cat', 'jumps', 'over']
['white', 'cat', 'jumps', 'over', 'the']
['cat', 'jumps', 'over', 'the', 'lazy']
['jumps', 'over', 'the', 'lazy', 'rabbit']
['over', 'the', 'lazy', 'rabbit']
['the', 'lazy', 'rabbit']


# Sliding window of size 2 for each word

In [12]:
neighbors = 2
for index, word in enumerate(tokenized_sentence):
    start = max(0, index - neighbors)
    finish = min(len(tokenized_sentence), index + neighbors + 1)
    print(word, tokenized_sentence[start:finish])

quick ['quick', 'and', 'cute']
and ['quick', 'and', 'cute', 'white']
cute ['quick', 'and', 'cute', 'white', 'cat']
white ['and', 'cute', 'white', 'cat', 'jumps']
cat ['cute', 'white', 'cat', 'jumps', 'over']
jumps ['white', 'cat', 'jumps', 'over', 'the']
over ['cat', 'jumps', 'over', 'the', 'lazy']
the ['jumps', 'over', 'the', 'lazy', 'rabbit']
lazy ['over', 'the', 'lazy', 'rabbit']
rabbit ['the', 'lazy', 'rabbit']


# Filter starting and ending words of sentences that do not have 2 neighbors around them

In [13]:
for index, word in enumerate(tokenized_sentence):
    if (index < neighbors) or (len(tokenized_sentence)-index < neighbors+1):
     print(index, word)
     continue

0 quick
1 and
8 lazy
9 rabbit


# Generate the training data for CBOW. CBOW predicts the middle word based on the context. We are creating a training data in the form of dictionary where keys are the middle words and values are the neighbors

In [14]:
training_data = {}

for index, word in enumerate(tokenized_sentence):
    if (index < neighbors) or (len(tokenized_sentence)-index < neighbors+1):
        continue
    else:
        start = index-neighbors
        finish = index+neighbors

        neighbor_words = tokenized_sentence[start:finish+1]

        print(word, neighbor_words[:neighbors]+neighbor_words[neighbors+1:])

        training_data[word] = neighbor_words[:neighbors]+neighbor_words[neighbors+1:]


cute ['quick', 'and', 'white', 'cat']
white ['and', 'cute', 'cat', 'jumps']
cat ['cute', 'white', 'jumps', 'over']
jumps ['white', 'cat', 'over', 'the']
over ['cat', 'jumps', 'the', 'lazy']
the ['jumps', 'over', 'lazy', 'rabbit']


In [15]:
training_data # key is the word and value is the context

{'cute': ['quick', 'and', 'white', 'cat'],
 'white': ['and', 'cute', 'cat', 'jumps'],
 'cat': ['cute', 'white', 'jumps', 'over'],
 'jumps': ['white', 'cat', 'over', 'the'],
 'over': ['cat', 'jumps', 'the', 'lazy'],
 'the': ['jumps', 'over', 'lazy', 'rabbit']}

# Create Vocab Dictionary

In [16]:
vocab = list(set(tokenized_sentence))

In [17]:
vocab

['rabbit',
 'cat',
 'the',
 'cute',
 'and',
 'white',
 'quick',
 'jumps',
 'over',
 'lazy']

In [18]:
vocab.sort()

In [19]:
vocab

['and',
 'cat',
 'cute',
 'jumps',
 'lazy',
 'over',
 'quick',
 'rabbit',
 'the',
 'white']

In [20]:
vocab_dict = {}

for index, word in enumerate(vocab):
    vocab_dict[word] = index

In [21]:
vocab_dict

{'and': 0,
 'cat': 1,
 'cute': 2,
 'jumps': 3,
 'lazy': 4,
 'over': 5,
 'quick': 6,
 'rabbit': 7,
 'the': 8,
 'white': 9}

# Convert training data into vectors

In [22]:
training_data # print the training data

{'cute': ['quick', 'and', 'white', 'cat'],
 'white': ['and', 'cute', 'cat', 'jumps'],
 'cat': ['cute', 'white', 'jumps', 'over'],
 'jumps': ['white', 'cat', 'over', 'the'],
 'over': ['cat', 'jumps', 'the', 'lazy'],
 'the': ['jumps', 'over', 'lazy', 'rabbit']}

In [23]:
training_data['the'] # we see the context to predicting "the"

['jumps', 'over', 'lazy', 'rabbit']

### the word **"quick"** is at 6th word in the vocab, if we put it in a one-hot vector format
### [0, 0, 0, 0, 0, 0, 1, 0, 0, 0]

  

# Create one hot vectors for each word

In [24]:
vocab_arrays = {}

for word, column_index in vocab_dict.items():
    word_array = np.zeros((1, len(vocab_dict)))
    word_array[0, column_index] = 1
    vocab_arrays[word] = word_array

In [25]:
vocab_arrays

{'and': array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 'cat': array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 'cute': array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]]),
 'jumps': array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]]),
 'lazy': array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]]),
 'over': array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]]),
 'quick': array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]]),
 'rabbit': array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]]),
 'the': array([[0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]]),
 'white': array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])}

# Generate Features and labels (Word2Vec to predict) to train Neural Network

In [26]:
word_size = len(vocab_dict)
training_size = len(training_data.items())
print(word_size)
print(" ")
print(training_size)

10
 
6


In [31]:
for index, train in enumerate(training_data.items()):
    word = train[0] # word to be predicted
    context = train[1]

In [32]:
word

'the'

In [33]:
context

['jumps', 'over', 'lazy', 'rabbit']

### Intialize features and labels

In [27]:
# Initialize the context vector
X = np.zeros([training_size, word_size])

# Initialize the word vectorto be predicted
y = np.zeros([training_size, word_size])

In [28]:
X

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
y

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

# Fill in X and y

In [30]:
for index, train in enumerate(training_data.items()):
  word = train[0]
  print(word, vocab_arrays[word])

cute [[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
white [[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
cat [[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
jumps [[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
over [[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
the [[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


In [34]:
for index, train in enumerate(training_data.items()):

    word = train[0]
    y[index,:] = vocab_arrays[word]
print(y) # The one hot vector for the words to be predicted

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


# Fill in X

In [35]:
for index, train in enumerate(training_data.items()):
  print(" ")
  print(" ")
  print(" ")
  print(train[1])
  for neighbour in train[1]:
    print(neighbour) # print neighbour words
    print(vocab_arrays[neighbour]) # one hot vectors for neighbor words



 
 
 
['quick', 'and', 'white', 'cat']
quick
[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
and
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
white
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
cat
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
 
 
 
['and', 'cute', 'cat', 'jumps']
and
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
cute
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
cat
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
jumps
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
 
 
 
['cute', 'white', 'jumps', 'over']
cute
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
white
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
jumps
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
over
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
 
 
 
['white', 'cat', 'over', 'the']
white
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
cat
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
over
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
the
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
 
 
 
['cat', 'jumps', 'the', 'lazy']
cat
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
jumps
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
the
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
lazy
[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
 
 
 
['jumps', 'over', 'la

# Sum of the Context Vectors

In [36]:
for index, train in enumerate(training_data.items()):

    word = train[0]
    y[index,:] = vocab_arrays[word]

    temp_array = np.zeros([1, word_size])

    for neighbour in train[1]:
        temp_array = temp_array+vocab_arrays[neighbour]

    X[index,:] = temp_array

In [37]:
X # Every row represents the sum of hot vector of the neighbors

array([[1., 1., 0., 0., 0., 0., 1., 0., 0., 1.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 0., 1., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1., 0., 0., 1., 1.],
       [0., 1., 0., 1., 1., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 1., 1., 0., 1., 0., 0.]])

# Average of context vectors

In [38]:
for index, train in enumerate(training_data.items()):

    word = train[0]
    y[index,:] = vocab_arrays[word]

    temp_array = np.zeros([1, word_size])

    for neighbour in train[1]:
        temp_array = temp_array+vocab_arrays[neighbour]

    X[index,:] = temp_array/(neighbors*2)

In [39]:
X

array([[0.25, 0.25, 0.  , 0.  , 0.  , 0.  , 0.25, 0.  , 0.  , 0.25],
       [0.25, 0.25, 0.25, 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.25, 0.25, 0.  , 0.25, 0.  , 0.  , 0.  , 0.25],
       [0.  , 0.25, 0.  , 0.  , 0.  , 0.25, 0.  , 0.  , 0.25, 0.25],
       [0.  , 0.25, 0.  , 0.25, 0.25, 0.  , 0.  , 0.  , 0.25, 0.  ],
       [0.  , 0.  , 0.  , 0.25, 0.25, 0.25, 0.  , 0.25, 0.  , 0.  ]])

In [40]:
y

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])

# Create and compile Neural Network

In [41]:
from keras.models import Sequential
from keras.layers import Dense

In [42]:
# Building model architecture
model = Sequential()
# Adding the hidden layer
model.add(Dense(4, input_dim=word_size, activation='relu')) # The 4 here is our choice. it is hidden layer.
# Adding the output layer
model.add(Dense(word_size, input_dim=4, activation='softmax'))

# Compiling the network
model.compile(
    loss='categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


# Train the NN

In [43]:
# Fitting our model, let's train for 1000
# epochs
model.fit(X, y, epochs=1000)

Epoch 1/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.1667 - loss: 2.2776
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.1667 - loss: 2.2755
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - accuracy: 0.1667 - loss: 2.2735
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.1667 - loss: 2.2714
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - accuracy: 0.1667 - loss: 2.2693
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - accuracy: 0.1667 - loss: 2.2672
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - accuracy: 0.1667 - loss: 2.2652
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.1667 - loss: 2.2630
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.1667 - loss: 2.2608
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.1667 - loss: 2.2586
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step - accuracy: 0.1667 - loss: 2.2564
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accura

# Get the predictions

In [44]:
# Storing the prediction
prediction = model.predict(X)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step


In [45]:
prediction.shape

(6, 10)

# Observe the Predictions

In [46]:
prediction[0].round(2) # This is about predicting "cute". In vocab_arrays see the one hot vector for "cute".
              # In predictions[0], the highest score is at index 2 which is in consistent with vocab_arrays for "cute"

array([0.01, 0.01, 0.53, 0.09, 0.  , 0.17, 0.  , 0.  , 0.  , 0.19],
      dtype=float32)

In [47]:
prediction[1].round(2)

array([0.  , 0.2 , 0.15, 0.  , 0.  , 0.08, 0.  , 0.  , 0.01, 0.55],
      dtype=float32)

In [48]:
training_data

{'cute': ['quick', 'and', 'white', 'cat'],
 'white': ['and', 'cute', 'cat', 'jumps'],
 'cat': ['cute', 'white', 'jumps', 'over'],
 'jumps': ['white', 'cat', 'over', 'the'],
 'over': ['cat', 'jumps', 'the', 'lazy'],
 'the': ['jumps', 'over', 'lazy', 'rabbit']}

In [49]:
vocab_arrays

{'and': array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 'cat': array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 'cute': array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]]),
 'jumps': array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]]),
 'lazy': array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]]),
 'over': array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]]),
 'quick': array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]]),
 'rabbit': array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]]),
 'the': array([[0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]]),
 'white': array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])}

# Convert predictions to binary form

In [50]:
for index, element in enumerate(prediction):
    predicted = element.argmax()
    prediction[index,:] = 0
    prediction[index, predicted] = 1

In [51]:
prediction

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]], dtype=float32)

### Let's check what word our model predicts as the center word given the surrounding words:

In [52]:
for index, sentence in enumerate(training_data.items()):
    print('For sentence: '+' '.join(sentence[1][0:2])+' '+' '.join(sentence[1][2:]))
    predicted_word = prediction[index]

    # Store keys and values from our dictionary
    for word, array_val in vocab_arrays.items():
        if np.array_equal(array_val[0], predicted_word):
            print('The center word predicted is: '+word)

For sentence: quick and white cat
The center word predicted is: cute
For sentence: and cute cat jumps
The center word predicted is: white
For sentence: cute white jumps over
The center word predicted is: cat
For sentence: white cat over the
The center word predicted is: jumps
For sentence: cat jumps the lazy
The center word predicted is: over
For sentence: jumps over lazy rabbit
The center word predicted is: the


# Check the embeddings which are our word vectors

In [53]:
embeddings = [layer.get_weights() for layer in model.layers]

In [54]:
embeddings

[[array([[ 1.9052683 ,  1.4958144 , -0.39007056, -0.5670846 ],
         [ 0.17239171,  1.1579099 ,  0.09611738, -0.47161433],
         [ 1.6885127 , -1.2052925 , -0.28375307,  1.6232948 ],
         [ 1.2751913 , -0.80956316, -0.04590362,  1.5113945 ],
         [-1.3587523 ,  0.80512244, -0.61861694,  0.82858455],
         [-1.0498762 , -0.91898626, -0.14562933,  0.44929492],
         [ 0.20965768,  0.7803329 , -0.50574887, -0.28104764],
         [-0.58172375, -1.3624957 , -0.04962349,  1.5411849 ],
         [-1.3193774 ,  1.2387408 ,  0.2878382 , -1.291301  ],
         [ 0.48093185, -0.705824  ,  0.06370846, -0.98435944]],
        dtype=float32),
  array([ 0.42871156,  0.9095898 , -0.09378436,  0.575216  ], dtype=float32)],
 [array([[-0.22836977,  1.3029698 ,  0.7688798 , -1.4045572 , -0.8899157 ,
          -0.51956433, -0.70432174, -0.96392554, -1.0546688 ,  1.4290241 ],
         [-0.6865222 , -1.6220046 ,  1.1075485 ,  1.0293361 , -1.0950412 ,
           1.6023449 , -0.60537606, -1.3

In [55]:
embeddings_layer_1 = embeddings[0][0]
embeddings_layer_2 = embeddings[1][0]

In [56]:
embeddings_layer_1

array([[ 1.9052683 ,  1.4958144 , -0.39007056, -0.5670846 ],
       [ 0.17239171,  1.1579099 ,  0.09611738, -0.47161433],
       [ 1.6885127 , -1.2052925 , -0.28375307,  1.6232948 ],
       [ 1.2751913 , -0.80956316, -0.04590362,  1.5113945 ],
       [-1.3587523 ,  0.80512244, -0.61861694,  0.82858455],
       [-1.0498762 , -0.91898626, -0.14562933,  0.44929492],
       [ 0.20965768,  0.7803329 , -0.50574887, -0.28104764],
       [-0.58172375, -1.3624957 , -0.04962349,  1.5411849 ],
       [-1.3193774 ,  1.2387408 ,  0.2878382 , -1.291301  ],
       [ 0.48093185, -0.705824  ,  0.06370846, -0.98435944]],
      dtype=float32)

In [57]:
embeddings_layer_1.shape

(10, 4)

Second example of Embeddings:

In [58]:
embeddings_layer_2

array([[-0.22836977,  1.3029698 ,  0.7688798 , -1.4045572 , -0.8899157 ,
        -0.51956433, -0.70432174, -0.96392554, -1.0546688 ,  1.4290241 ],
       [-0.6865222 , -1.6220046 ,  1.1075485 ,  1.0293361 , -1.0950412 ,
         1.6023449 , -0.60537606, -1.312613  , -1.3888642 ,  0.31056833],
       [ 0.5076804 ,  0.05297893,  0.26975963, -0.5293294 ,  0.48394102,
        -0.64958346, -0.6337056 , -0.52396846, -0.20837401,  0.46213526],
       [-1.2724644 ,  1.2412994 , -0.92057115, -1.5950087 , -0.6497004 ,
         0.44840303, -1.1239413 , -0.61558646,  1.58234   ,  0.48392856]],
      dtype=float32)

In [59]:
embeddings_layer_2.shape

(4, 10)

In [60]:
vocab_dict

{'and': 0,
 'cat': 1,
 'cute': 2,
 'jumps': 3,
 'lazy': 4,
 'over': 5,
 'quick': 6,
 'rabbit': 7,
 'the': 8,
 'white': 9}

### let's see the embedding for the word "cute" stored in the first layer:

In [61]:
embeddings_layer_1[2]

array([ 1.6885127 , -1.2052925 , -0.28375307,  1.6232948 ], dtype=float32)

### For the word "lazy":

In [62]:
embeddings_layer_1[4]

array([-1.3587523 ,  0.80512244, -0.61861694,  0.82858455], dtype=float32)

### Word vector is the average of both embeddings

In [63]:
word_vectors = (embeddings_layer_2.T+embeddings_layer_1)/2

In [64]:
word_vectors

array([[ 0.83844924,  0.40464613,  0.05880493, -0.91977453],
       [ 0.7376808 , -0.23204738,  0.07454816,  0.38484251],
       [ 1.2286962 , -0.04887199, -0.00699672,  0.35136184],
       [-0.06468296,  0.10988647, -0.28761652, -0.04180712],
       [-1.124334  , -0.14495936, -0.06733796,  0.08944207],
       [-0.7847203 ,  0.3416793 , -0.3976064 ,  0.44884896],
       [-0.24733204,  0.08747843, -0.56972724, -0.7024945 ],
       [-0.77282465, -1.3375543 , -0.28679597,  0.46279922],
       [-1.1870232 , -0.07506168,  0.03973209,  0.1455195 ],
       [ 0.954978  , -0.19762784,  0.26292187, -0.25021544]],
      dtype=float32)