<a href="https://colab.research.google.com/github/IrumShehryar/ML-NLP-Coursework/blob/main/ml/04-classification-models/Naive_bayes/Project_01_NaiveBayes_a_Probabilistic_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB

# Generating Data

In [2]:
X = np.array([3.77, 2.47, 2.19, 0.21, 1.63, 1.69, 5.09, 4.23, 5.02, 4.41, 4.729, 6.01]).reshape(-1,1)
y = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

# X is the size of tumor.

# y is 0 or 1.
# 0 means no cancer
# 1 means cancer

In [6]:
X

array([[3.77 ],
       [2.47 ],
       [2.19 ],
       [0.21 ],
       [1.63 ],
       [1.69 ],
       [5.09 ],
       [4.23 ],
       [5.02 ],
       [4.41 ],
       [4.729],
       [6.01 ]])

# Training

In [3]:
log_reg = LogisticRegression()
LR = log_reg.fit(X,y)

# Get Prediction from unseen value

In [5]:
X_test = np.array([3.50]).reshape(-1,1)
X_test.shape

(1, 1)

# Getting Probabilities of prediction

In [7]:
LR.predict_proba(X_test)

array([[0.54112337, 0.45887663]])

# Getting  class prediction

In [8]:
y_pred = LR.predict(X_test)

In [9]:
y_pred

array([0])

# Applying Naive Bayes Classifier

In [10]:
NB_model = GaussianNB()

In [11]:
NB_model.fit(X,y)

GaussianNB()

# Testing Naive Bayes Classifier

In [12]:
X_test = np.array([3.50]).reshape(-1,1)

In [13]:
NB_model.predict_proba(X_test)

array([[0.80088133, 0.19911867]])

In [14]:
y_pred_NB =NB_model.predict(X_test)

In [15]:
y_pred_NB

array([0])